set nocompatible
syntax on

" this statusline is used unless powerline is installed
set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)

set laststatus=2
set modeline

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

filetype plugin on
filetype indent on

autocmd FileType python setlocal shiftwidth=2 tabstop=2 softtabstop=2 expandtab
autocmd FileType html setlocal tabstop=2 shiftwidth=2 softtabstop=2 expandtab 
autocmd Filetype changes setlocal tw=67

